<?php

/**
 * Implements hook_enable().
 */
function commerce_google_tag_manager_enable() {
  $weight = db_query("SELECT weight FROM {system} WHERE name = :module", array(':module' => 'google_tag'))->fetchField();

  // Update the weight so its hooks get called after the actual GTM module.
  db_update('system')
          ->fields(array('weight' => max(1000, $weight + 1)))
          ->condition('name', 'commerce_google_tag_manager')
          ->execute();
}
